# Generated by Django 4.0.6 on 2022-07-14 23:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('series_slug', models.SlugField(unique=True, verbose_name='Series slug')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('article_slug', models.SlugField(unique=True, verbose_name='Article slug')),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Modified')),
                ('series', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.articleseries', verbose_name='Series')),
            ],
            options={
                'verbose_name_plural': 'Article',
                'ordering': ['-publish_date'],
            },
        ),
    ]
